<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"班级/年级管理",
                        "menuJump":"列表",
                        "tableName":"banjinianji"
                    }
                ],
                "menu":"班级/年级管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"教育经历管理",
			            "menuJump":"列表",
			            "tableName":"jiaoyujingli"
			        }
			    ],
			    "menu":"教育经历管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"档案信息管理",
                        "menuJump":"列表",
                        "tableName":"dangan"
                    }
                ],
                "menu":"档案信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"档案类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryDangan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"职务类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJiaoyujingli"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }

                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"留言信息管理",
                        "menuJump":"列表",
                        "tableName":"liuyanxinxi"
                    }
                ],
                "menu":"留言信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"班级/年级管理",
	                    "menuJump":"列表",
	                    "tableName":"banjinianji"
	                }
	            ],
	            "menu":"班级/年级管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"教育经历管理",
			            "menuJump":"列表",
			            "tableName":"jiaoyujingli"
			        }
			    ],
			    "menu":"教育经历管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"档案信息管理",
	                    "menuJump":"列表",
	                    "tableName":"dangan"
	                }
	            ],
	            "menu":"档案信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增"
	                    ],
	                    "menu":"留言信息管理",
	                    "menuJump":"列表",
	                    "tableName":"liuyanxinxi"
	                }
	            ],
	            "menu":"留言信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"学生",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
